language: bash
services: docker
os: windows
before_script:
  - docker version
script:
  - |
    (
      set -Eeuo pipefail
      set -x
      df -h
      docker build --no-cache --tag danielwhatmuff/aspnetapp-travis-example:latest --file Dockerfile.windowsservercore-ltsc2016 .
      df -h
      docker run --name aspnet_sample --rm -it -p 8000:80 danielwhatmuff/aspnetapp-travis-example:latest --stop-timeout 5
      df -h
    )
