version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version

build_script:
  - docker build --no-cache --tag danielwhatmuff.azurecr.io/aspnetapp-travis-example:latest .

deploy_script:
  - docker login -u=%DOCKER_USER% -p=%DOCKER_PASS% danielwhatmuff.azurecr.io
  - docker push danielwhatmuff.azurecr.io/aspnetapp-travis-example:latest

environment:
  DOCKER_USER:
    secure: oL1+uXJyvnV5e1qo7eCwzg==
  DOCKER_PASS:
    secure: oazr6UiEX9csdOFeZVPhWe7388uiLj1+zCaOcqdqmfEm26tPHza8JHSl8ZFAQKYc
