version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version

build_script:
  - docker build --no-cache --tag danielwhatmuff/aspnetapp-travis-example:latest .

test_script:
  - docker run --name aspnet_sample --rm -it -p 8000:80 danielwhatmuff/aspnetapp-travis-example:latest --stop-timeout 5
