---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world-dotnet
        image: quay.io/{{.QUAY_ORG}}/{{.QUAY_REPO}}:latest
        ports:
          - containerPort: 80
